# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0007_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
