# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='photo',
            field=models.ImageField(default='static/engineerimages/defaultengineerimage.png', upload_to='static/engineerimages'),
        ),
    ]
