# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerApp', '0002_auto_20161207_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='photo',
            field=models.ImageField(default=0, upload_to='static/engineerimages'),
        ),
    ]
