# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0001_initial'),
        ('CommentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cemail',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='comment',
            name='cname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GroupsApp.Group'),
        ),
    ]
