# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookmarkApp', '0001_initial'),
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bookmarks',
            field=models.ManyToManyField(to='BookmarkApp.Bookmark'),
        ),
    ]
